config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/comments'

  resources :authorizations, only: [] do
    collection do
      get 'get_vk_token'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'admin', to: 'devise/sessions#new', as: :sign_in
  end

  resources :articles do
    member do
      patch 'upload_file'
      get 'download_file'
      get 'delete_file'
      post 'create_comment'
      get 'edit_comment'
      get 'remove_comment'
    end
    collection do
      post 'upload_file'
      get 'load_editor_image'
      post 'upload_image'
      get 'tutorial'
    end
  end
  resources :tags
  resources :categories
  resources :comments, only: [:new, :create, :destroy, :index]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:comments]

  def about
  end

  def contact
  end

  def comments
    @comments = Article.all.map{|x| [x.title, x.comments]}.select{|x| x[1].size > 0}
    @contact_comments = Comment.order(:created_at).all.page params[:page]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>Зачем нужен этот сайт.</h1>
<p>В первую очередь, он нужен для структурирования знаний в области IT,
  к тому же, материалы, представленные на сайте, могут быть полезны
  и для обычного посетителя.</p>
<br><br>
<p><small>Сайт написан на <b>Ruby on Rails</b>.<br>
Статьи формируются с использованием <a href='https://pandao.github.io/editor.md/en.html'>editor.md</a>
и языка разметки <b>markdown</b>.</small></p>

app/views/static_pages/comments.haml
- @comments.each do |data|
  %p= data[0]
  - data[1].each do |comment|
    - @item = comment.article
    = render 'articles/comment', comment: comment

%hr
%h3 Комментарии со страницы Contact
- @contact_comments.each do |comment|
  %p= comment.content
  %hr

= paginate @contact_comments

app/views/static_pages/contact.haml
%h2.center Если не получилось связаться, можно оставить информацию здесь.
%br
.row
  .col-md-12
    %small
      Максимум 500 символов
      %span.countdown
.row
  .col-md-12
    = form_for :comment, url: comments_path do |f|
      .row
        .col-md-12
          = f.text_area :content, size: "50x10", class: "message"
      .row
        .col-md-12
          %br
          = f.submit "Отправить", class: "btn btn-large btn-primary"