config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/comments'

  resources :authorizations, only: [] do
    collection do
      get 'get_vk_token'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'admin', to: 'devise/sessions#new', as: :sign_in
  end

  resources :articles do
    member do
      patch 'upload_file'
      get 'download_file'
      get 'delete_file'
      post 'create_comment'
      get 'edit_comment'
      get 'remove_comment'
    end
    collection do
      post 'upload_file'
      get 'load_editor_image'
      post 'upload_image'
      get 'tutorial'
    end
  end
  resources :tags
  resources :categories
  resources :comments, only: [:new, :create, :destroy, :index]
end

app/models/article/tag.rb
class Article::Tag < ApplicationRecord
  has_and_belongs_to_many :articles

  validates :name, presence: true, uniqueness: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :articles

  validates :name, presence: true, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_breadcrumbs
  before_action :set_tag, only: %i(show edit update destroy)

  def index
    @items = Tag.all
  end

  def new
    @item = Tag.new
  end

  def create
    @item = Tag.new(tag_params)
    if @item.save
      redirect_to tags_path, flash: {success: 'Тег успешно создан'}
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update_attributes(tag_params)
      redirect_to tag_path(@item), flash: {success: 'Тег успешно обновлен'}
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to tags_path, flash: {success: 'Тег успешно удален'}
    else
      redirect_to tags_path, flash: {error: 'Тег не удален'}
    end
  end

  private

  def set_tag
    @item = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.haml
= form_for @item do |f|
  .form-group.col-md-3.col-sm-12
    = f.label :name, class: 'col-form-label'
    = f.text_field :name, autofocus: true, class: 'form-control'

  .actions.col-md-3.col-sm-4
    = f.submit t("tags.#{params[:action]}"), class: 'btn btn-outline-secondary'

app/views/tags/edit.haml
%h1= t('tags.edit').capitalize
= render 'form'

app/views/tags/index.haml
%h1= t('tags.index').capitalize

.col-12
  .row.tags-index
    - @items.each do |tag|
      %span.badge.badge-pill.badge-secondary
        = tag.name
        - if tag.name != 'Tutorial'
          = link_to content_tag(:i, nil, class: 'fa fa-pencil'),
            edit_tag_path(tag)
          = link_to content_tag(:i, nil, class: 'fa fa-trash'), tag_path(tag),
            method: :delete, data: { confirm: 'Вы уверены?' }

.col-12
  .create-btn.row
    = link_to t('tags.new'), new_tag_path, class: 'btn btn-outline-secondary'

app/views/tags/new.haml
%h1= t('tags.new').capitalize
= render 'form'

app/views/tags/show.haml
%h1= t('tags.show').capitalize

%span.badge.badge-pill.badge-secondary
  = @item.name
  - if tag.name != 'Tutorial'
    = link_to content_tag(:i, nil, class: 'fa fa-pencil'), edit_tag_path(@item)
    = link_to content_tag(:i, nil, class: 'fa fa-trash'), tag_path(@item),
      method: :delete, data: { confirm: 'Вы уверены?' }