config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/comments'

  resources :authorizations, only: [] do
    collection do
      get 'get_vk_token'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'admin', to: 'devise/sessions#new', as: :sign_in
  end

  resources :articles do
    member do
      patch 'upload_file'
      get 'download_file'
      get 'delete_file'
      post 'create_comment'
      get 'edit_comment'
      get 'remove_comment'
    end
    collection do
      post 'upload_file'
      get 'load_editor_image'
      post 'upload_image'
      get 'tutorial'
    end
  end
  resources :tags
  resources :categories
  resources :comments, only: [:new, :create, :destroy, :index]
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_breadcrumbs
  before_action :set_category, only: %i(show edit update destroy)

  def index
    @items = Category.all
  end

  def new
    @item = Category.new
  end

  def create
    @item = Category.new(category_params)
    if @item.save
      redirect_to categories_path, flash: {success: 'Категория успешно создана'}
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update_attributes(category_params)
      redirect_to category_path(@item), flash: {success: 'Категория успешно обновлена'}
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to categories_path, flash: {success: 'Категория успешно удалена'}
    else
      redirect_to categories_path, flash: {error: 'Категория не удалена'}
    end
  end

  private

  def set_category
    @item = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.haml
= form_for @item do |f|
  .form-group.col-md-3.col-sm-12
    = f.label :name, class: 'col-form-label'
    = f.text_field :name, autofocus: true, class: 'form-control'

  .actions.col-md-3.col-sm-4
    = f.submit t("categories.#{params[:action]}"),
      class: 'btn btn-outline-secondary'

app/views/categories/edit.haml
%h1= t('categories.edit').capitalize
= render 'form'

app/views/categories/index.haml
%h1= t('categories.index').capitalize

.col-12
  .row.tags-index
    - @items.each do |category|
      %span.badge.badge-pill.badge-secondary
        = category.name
        = link_to content_tag(:i, nil, class: 'fa fa-pencil'),
          category_path(category)
        = link_to content_tag(:i, nil, class: 'fa fa-trash'),
          category_path(category),
          method: :delete, data: { confirm: 'Вы уверены?' }

.col-12
  .create-btn.row
    = link_to t('categories.new'), new_category_path,
      class: 'btn btn-outline-secondary'

app/views/categories/new.haml
%h1= t('categories.new').capitalize
= render 'form'

app/views/categories/show.haml
%h1= t('categories.show').capitalize

%span.badge.badge-pill.badge-secondary
  = @item.name
  = link_to content_tag(:i, nil, class: 'fa fa-pencil'),
    edit_category_path(@item)
  = link_to content_tag(:i, nil, class: 'fa fa-trash'), category_path(@item),
    method: :delete, data: { confirm: 'Вы уверены?' }