config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/comments'

  resources :authorizations, only: [] do
    collection do
      get 'get_vk_token'
    end
  end

  devise_for :users, controllers: { sessions: 'sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }
  as :user do
    get 'admin', to: 'devise/sessions#new', as: :sign_in
  end

  resources :articles do
    member do
      patch 'upload_file'
      get 'download_file'
      get 'delete_file'
      post 'create_comment'
      get 'edit_comment'
      get 'remove_comment'
    end
    collection do
      post 'upload_file'
      get 'load_editor_image'
      post 'upload_image'
      get 'tutorial'
    end
  end
  resources :tags
  resources :categories
  resources :comments, only: [:new, :create, :destroy, :index]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_auth_user, :save_previous_redirect

  def set_breadcrumbs
    @need_restful_breadcrumbs = true
  end

  def current_auth_user
    user = AuthUser.find_by(unique_id: session[:unique_id])
    if Rails.env.production? && user.present? &&
      (user.updated_at + user.expires_in.to_i) < Time.current
      session.delete(:unique_id)
    end
    @auth_user = ((session[:unique_id].present? && AuthUser.find_by(id: user.try(:id))) ? user : nil)
  end

  def save_previous_redirect
    session[:unique_id] = 'qwerty' if Rails.env.development?
    # session[:return_to] ||= request.referer
  end

  protected

  def authenticate_user!
    if user_signed_in?
      super
    else
      render file: File.join(Rails.root, 'public/404'), formats: [:html],
        status: 404, layout: false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-info"
    end
  end

  def vk_url
    redirect_uri = "https://#{request.domain}/authorizations/get_vk_token"
    session[:vk_redirect_uri] = redirect_uri
    params = {
      client_id: '6716551',
      redirect_uri: redirect_uri,
      scope: '0',
      response_type: 'code',
      v: Socials::API::VK::VERSION,
      state: Digest::MD5.hexdigest(Time.current.to_s)
    }
    a = []
    params.each{|k, v| a << "#{k}=#{v}"}
    link = "https://oauth.vk.com/authorize?#{a.join(?&)}"
  end
end

app/views/application/_breadcrumbs.haml
- controller = params[:controller]
- action = params[:action]
- if @need_restful_breadcrumbs
  .row
    .col-md-12
      %ul.breadcrumb
        - if controller == 'articles' && action == 'show'
          - if session[:tutorial]
            %li.breadcrumb-item= link_to t(controller + '.index'), tutorial_articles_path
          - else
            %li.breadcrumb-item= link_to t(controller + '.index'), root_path
          %li.breadcrumb-item.active= t(controller + '.show')
        - else
          - case action
          - when 'index', 'tutorial'
            %li.breadcrumb-item.active= t(controller + '.index')
          - when 'show'
            %li.breadcrumb-item= link_to t(controller + '.index'),
              '/' + controller
            %li.breadcrumb-item.active= t(controller + '.show')
          - when 'new', 'create'
            %li.breadcrumb-item= link_to t(controller + '.index'),
              '/' + controller
            %li.breadcrumb-item.active= t(controller + '.new')
          - when 'edit', 'update'
            %li.breadcrumb-item= link_to t(controller + '.index'),
              '/' + controller
            %li.breadcrumb-item= link_to t(controller + '.show'),
              '/' + controller + '/' + item.id.to_s
            %li.breadcrumb-item.active= t(controller + '.edit')

app/views/application/_flash.haml
- flash.each do |key, value|
  - if %(error alert notice success).include? key.to_s
    %div{ class: flash_class(key), role: 'alert' }
      %button.close{ name: 'button', type: 'button', 'data-dismiss': 'alert' }
        ×
      = value.html_safe

app/views/application/_sidebar.haml
%aside.hidden-print#sidebar-wrapper
  .sidebar-nav
    - if user_signed_in?
      .admin-panel
        .child-admin-panel
          %h5 Панель админа
        .child-admin-panel
          = link_to t('categories.index').capitalize, categories_path,
            class: 'link'
          = link_to t('tags.index').capitalize, tags_path, class: 'link'
          = link_to 'Выход', destroy_user_session_path,
            class: 'log-out-icon link'
        .child-admin-panel
          = link_to t('articles.new').capitalize, new_article_path,
            class: 'link'

    #author-info
      = image_tag 'a2', id: 'avatar'
      %strong David
      %p Join me&nbsp;
      .social-media-icons
        %ul
          %li
            %a.twitter{ href: 'https://vk.com/hot_dav', target: '_blank' }
              %i.fa.fa-vk
          %li
            %a.facebook{ href: 'https://github.com/Davhot', target: '_blank' }
              %i.fa.fa-github
          %li
            %a.instagram{ href: 'https://www.instagram.com/dav_hot', target: '_blank' }
              %i.fa.fa-instagram
    %hr.sidebar-content-separate
    .menu-container.menu-primary#menu-primary{ role: 'navigation' }
      %nav.menu
        %ul.menu-primary-items#menu-primary-items
          %li= link_to 'Home', root_path, class: 'link'
          %li= link_to 'Tutorial', tutorial_articles_path, class: 'link'
          %li= link_to 'About', static_pages_about_path, class: 'link'
    .d-none.d-sm-block
      %hr.sidebar-content-separate
      = simple_form_for Article.search(params).ransack(params[:q]), url: articles_path, method: :get do |f|
        = f.input :title_or_content_or_describe_cont,
          label: false,
          required: false,
          input_html: {class: 'form-control ds-input', autocomplete: 'off',
            placeholder: 'Поиск...', type: 'search' }
        = f.submit 'Go'
    %hr.sidebar-content-separate
    %div
      %h6 Последние посты
      %ul.links-sidebar
        - Article.all.first(5).each do |article|
          %li= link_to content_tag(:p, article.title), article_path(article),
            class: 'link'
    %hr.sidebar-content-separate
    %div
      %h6 Категории
      %ul.links-sidebar
        - Category.all.each do |category|
          %li= link_to content_tag(:p, category.name),
            articles_path(category_id: category.id), class: 'link'
    %hr.sidebar-content-separate
    #tags
      %h6 Теги
      - Tag.all.each do |tag|
        = link_to content_tag(:span, tag.name,
          class: 'badge badge-pill badge-secondary'),
          articles_path(tag_id: tag.id)
    %hr.sidebar-content-separate
    = image_tag 'log-data-logo-white.png', id: 'logo',
      title: 'log-data-logo-white'

app/views/application/_time.haml
%p.card-text= "#{I18n.l(created_time, format: '%d.%m.%Y')} (обновлено: #{I18n.l(updated_time, format: '%d.%m.%Y')})"